spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5tPGHd4Fx1iBmJaazHFe
      secret-key:  vHKaTIkiiQABFNRoqILiteZ4UqrpWc
      oss:
        bucket: web-tiase
        endpoint: oss-cn-hangzhou.aliyuncs.com
#      # 发送短信接口的配置
#      sms:
#        host: http://dingxin.market.alicloudapi.com
#        path: /dx/sendSms
#        appcode: #
    sentinel:
      transport:
        dashboard: localhost:8080

  application:
    name: gulimall-third

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
