spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


    sentinel:
      transport:
        dashboard: localhost:8080

  application:
    name: gulimall-third

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
