spring:
  zipkin:
    base-url: http://192.168.100.100:9411
    sender:
      type: web
    discovery-client-enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:8848

#      # 发送短信接口的配置
#      sms:
#        host: http://dingxin.market.alicloudapi.com
#        path: /dx/sendSms
#        appcode: #
    sentinel:
      transport:
        dashboard: 192.168.100.100:8080

  application:
    name: gulimall-third

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'
